---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - cascade.gideonsanni.dev
  resources:
  - cascadepolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cascade.gideonsanni.dev
  resources:
  - cascadepolicies/finalizers
  verbs:
  - update
- apiGroups:
  - cascade.gideonsanni.dev
  resources:
  - cascadepolicies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.istio.io
  resources:
  - destinationrules
  verbs:
  - get
  - list
  - patch
  - update
  - watch
