#!/usr/bin/env bash
# Switches an already-deployed operator (hack/deploy-operator.sh) from the
# default cluster-wide ClusterRole to namespace-scoped Role/RoleBinding
# pairs — docs/security-threat-model.md's own named production-hardening
# step ("Narrowing it to a Role+RoleBinding per watched namespace").
#
# This is a separate, explicit, opt-in script rather than a step folded
# into hack/deploy-operator.sh: unlike that script's other steps
# (cert-manager, RBAC bindings, scrape config), this one changes real
# application behavior — which namespaces the operator can see
# CascadePolicy objects in at all — not just tightens permissions
# invisibly. A CascadePolicy created in a namespace not listed here after
# running this will be silently invisible to the operator (never
# reconciled, no error logged, since the cache never watches it) — the
# same "unwatched" experience as an operator instance that's simply not
# been given that namespace, which is the whole point of restricting the
# watch, but worth calling out plainly.
#
# Usage:
#   NAMESPACES=default,linkerd-demo hack/switch-to-namespaced-rbac.sh
#
# To revert: re-run `make deploy` (recreates the cluster-wide
# ClusterRoleBinding this script deletes) and unset WATCH_NAMESPACES:
#   kubectl -n cascade-operator-system set env deployment/cascade-operator-controller-manager WATCH_NAMESPACES-
#   make deploy IMG=cascade-operator:dev
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OPERATOR_NS="cascade-operator-system"
DEPLOYMENT="cascade-operator-controller-manager"

if [[ -z "${NAMESPACES:-}" ]]; then
  echo "usage: NAMESPACES=ns1,ns2 $0" >&2
  exit 1
fi

echo "== [1/3] apply namespaced Role/RoleBinding for: ${NAMESPACES} =="
NAMESPACES="${NAMESPACES}" bash "${ROOT}/hack/generate-namespaced-rbac.sh" | kubectl apply -f -

echo "== [2/3] remove the cluster-wide ClusterRoleBinding =="
# Deletes only the *binding*, not the ClusterRole object itself — an
# unbound ClusterRole grants nothing to anyone, so leaving it defined
# (still generated by config/rbac/role.yaml, re-created on the next
# `make deploy` regardless) is harmless and keeps this step reversible
# with a single `make deploy` rather than needing to also recreate the
# ClusterRole from scratch.
kubectl delete clusterrolebinding cascade-operator-manager-rolebinding --ignore-not-found

echo "== [3/3] restrict the watch to the same namespaces via WATCH_NAMESPACES =="
kubectl -n "${OPERATOR_NS}" set env "deployment/${DEPLOYMENT}" "WATCH_NAMESPACES=${NAMESPACES}"
kubectl -n "${OPERATOR_NS}" rollout status "deployment/${DEPLOYMENT}" --timeout=120s

echo "== done =="
echo "Confirm with:"
echo "  kubectl -n ${OPERATOR_NS} logs deploy/${DEPLOYMENT} | grep -i 'Restricting CascadePolicy watches'"
echo "  kubectl auth can-i list cascadepolicies --as=system:serviceaccount:${OPERATOR_NS}:cascade-operator-controller-manager -A"
echo "  (should now report 'no' for -A, and 'yes' with -n <one of ${NAMESPACES}>)"
